<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 2,
                'name' => 'Leonardo',
                'email' => 'leo@mail.com',
                'password' => '$2y$10$daXY3g2kOoBSTaF/kygmauk8J6xai1CumeyBRZhzBMwERQKEPIGoq',
                'remember_token' => NULL,
                'last_logged_in_at' => NULL,
                'locale' => 'en_ES',
                'enabled' => true,
                'created_at' => '2022-01-26 01:26:40',
                'updated_at' => '2022-01-26 01:26:40',
                'deleted_at' => NULL,
                'contact_id' => 2,
                'employer_cost' => NULL,
                'competencies' => '[]',
                'working_skills' => '[]',
                'work_experience' => NULL,
                'contract_type' => NULL,
                'contract_start' => NULL,
                'contract_end' => NULL,
                'surname' => 'Arregui',
                'personal_phone' => '0995650300',
                'date_birth' => NULL,
                'gender' => NULL,
                'job_title' => NULL,
                'business_phone' => NULL,
                'photo' => NULL,
                'personal_notes' => NULL,
                'company_id' => NULL,
            ),
            1 => 
            array (
                'id' => 3,
                'name' => 'Silvia',
                'email' => 'silvia@mail.com',
                'password' => '$2y$10$Z7TrM0JuCx9X58fV7cZzzuZHweJ6aGr2zLuTzek1fx2lpT8eUpa3e',
                'remember_token' => NULL,
                'last_logged_in_at' => NULL,
                'locale' => 'en_ES',
                'enabled' => true,
                'created_at' => '2022-01-26 01:27:24',
                'updated_at' => '2022-01-26 01:27:24',
                'deleted_at' => NULL,
                'contact_id' => 3,
                'employer_cost' => NULL,
                'competencies' => '[]',
                'working_skills' => '[]',
                'work_experience' => NULL,
                'contract_type' => NULL,
                'contract_start' => NULL,
                'contract_end' => NULL,
                'surname' => 'Lugo',
                'personal_phone' => '0995650300',
                'date_birth' => NULL,
                'gender' => 'gender_02',
                'job_title' => NULL,
                'business_phone' => NULL,
                'photo' => NULL,
                'personal_notes' => NULL,
                'company_id' => NULL,
            ),
            2 => 
            array (
                'id' => 4,
                'name' => 'Judith',
                'email' => 'judith@mail.com',
                'password' => '$2y$10$7yW3EO4CLcMUNmSzS68G6Oh6R8v/4oxvo4I3Ld3xDuxHjtxThQD06',
                'remember_token' => NULL,
                'last_logged_in_at' => NULL,
                'locale' => 'en_ES',
                'enabled' => true,
                'created_at' => '2022-01-26 01:36:22',
                'updated_at' => '2022-01-26 01:36:22',
                'deleted_at' => NULL,
                'contact_id' => 4,
                'employer_cost' => NULL,
                'competencies' => '[]',
                'working_skills' => '[]',
                'work_experience' => NULL,
                'contract_type' => NULL,
                'contract_start' => NULL,
                'contract_end' => NULL,
                'surname' => 'CRE',
                'personal_phone' => '0995650300',
                'date_birth' => NULL,
                'gender' => NULL,
                'job_title' => NULL,
                'business_phone' => NULL,
                'photo' => NULL,
                'personal_notes' => NULL,
                'company_id' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'name' => 'GAE',
                'email' => 'gae@mail.com',
                'password' => '$2y$10$STrN64ya9ZK7UBnXEYaIP.CwDsCYqi7q5jdlgByw4qVO9gw/vwMkC',
                'remember_token' => NULL,
                'last_logged_in_at' => NULL,
                'locale' => 'en_ES',
                'enabled' => true,
                'created_at' => '2022-01-26 01:37:45',
                'updated_at' => '2022-01-26 01:37:45',
                'deleted_at' => NULL,
                'contact_id' => 5,
                'employer_cost' => NULL,
                'competencies' => '[]',
                'working_skills' => '[]',
                'work_experience' => NULL,
                'contract_type' => NULL,
                'contract_start' => NULL,
                'contract_end' => NULL,
                'surname' => 'GAE',
                'personal_phone' => '0995650300',
                'date_birth' => NULL,
                'gender' => NULL,
                'job_title' => NULL,
                'business_phone' => NULL,
                'photo' => NULL,
                'personal_notes' => NULL,
                'company_id' => NULL,
            ),
            4 => 
            array (
                'id' => 1,
                'name' => 'Administrador',
                'email' => 'admin@admin.com',
                'password' => '$2y$10$TsPyKbi/4JWsRj.8955kxe849smb2rNLUlY4yaMH/J6mlRVKvfAP.',
                'remember_token' => NULL,
                'last_logged_in_at' => '2022-01-25 22:48:01',
                'locale' => 'es_ES',
                'enabled' => true,
                'created_at' => '2022-01-25 20:20:13',
                'updated_at' => '2022-01-25 22:48:01',
                'deleted_at' => NULL,
                'contact_id' => 1,
                'employer_cost' => NULL,
                'competencies' => NULL,
                'working_skills' => NULL,
                'work_experience' => NULL,
                'contract_type' => NULL,
                'contract_start' => NULL,
                'contract_end' => NULL,
                'surname' => NULL,
                'personal_phone' => NULL,
                'date_birth' => NULL,
                'gender' => NULL,
                'job_title' => NULL,
                'business_phone' => NULL,
                'photo' => NULL,
                'personal_notes' => NULL,
                'company_id' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Cordinador',
                'email' => 'cordinadorguayas@mail.com',
                'password' => '$2y$10$kiBAOqYC1T9fS94S8zJ/Me.lDMBROFVooN/gTUsww0L7YTRF/VFJu',
                'remember_token' => NULL,
                'last_logged_in_at' => NULL,
                'locale' => 'en_ES',
                'enabled' => true,
                'created_at' => '2022-01-26 03:53:01',
                'updated_at' => '2022-01-26 03:53:01',
                'deleted_at' => NULL,
                'contact_id' => 6,
                'employer_cost' => NULL,
                'competencies' => '[]',
                'working_skills' => '[]',
                'work_experience' => NULL,
                'contract_type' => NULL,
                'contract_start' => NULL,
                'contract_end' => NULL,
                'surname' => 'Local Guayas',
                'personal_phone' => '0995650300',
                'date_birth' => NULL,
                'gender' => NULL,
                'job_title' => NULL,
                'business_phone' => NULL,
                'photo' => NULL,
                'personal_notes' => NULL,
                'company_id' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Coordinador',
                'email' => 'coordinadorproyectos@mail.com',
                'password' => '$2y$10$MvbZac3S1xx.WipMFOPgYeaZWCvaSaB9bK.0JeKA81fONeNW7lcVG',
                'remember_token' => NULL,
                'last_logged_in_at' => NULL,
                'locale' => 'en_ES',
                'enabled' => true,
                'created_at' => '2022-01-26 03:53:45',
                'updated_at' => '2022-01-26 03:53:45',
                'deleted_at' => NULL,
                'contact_id' => 7,
                'employer_cost' => NULL,
                'competencies' => '[]',
                'working_skills' => '[]',
                'work_experience' => NULL,
                'contract_type' => NULL,
                'contract_start' => NULL,
                'contract_end' => NULL,
                'surname' => 'Proyectos',
                'personal_phone' => '0995650300',
                'date_birth' => NULL,
                'gender' => NULL,
                'job_title' => NULL,
                'business_phone' => NULL,
                'photo' => NULL,
                'personal_notes' => NULL,
                'company_id' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Tecnico',
                'email' => 'tadministrativo@mail.com',
                'password' => '$2y$10$8W81.Od4/qDssdwLJLwyNOlYyAGULqmRvSDi5cnBxfQw5nk7zkC7C',
                'remember_token' => NULL,
                'last_logged_in_at' => NULL,
                'locale' => 'en_ES',
                'enabled' => true,
                'created_at' => '2022-01-26 03:54:43',
                'updated_at' => '2022-01-26 03:54:43',
                'deleted_at' => NULL,
                'contact_id' => 8,
                'employer_cost' => NULL,
                'competencies' => '[]',
                'working_skills' => '[]',
                'work_experience' => NULL,
                'contract_type' => NULL,
                'contract_start' => NULL,
                'contract_end' => NULL,
                'surname' => 'Administrativo',
                'personal_phone' => '0995650300',
                'date_birth' => NULL,
                'gender' => NULL,
                'job_title' => NULL,
                'business_phone' => NULL,
                'photo' => NULL,
                'personal_notes' => NULL,
                'company_id' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Oficial',
                'email' => 'oficialpresupuestolocal@mail.com',
                'password' => '$2y$10$jH71CkaWSkpecuJnndFLruo2CWwt/6jaQelaG82G5YChcI/xywEne',
                'remember_token' => NULL,
                'last_logged_in_at' => NULL,
                'locale' => 'en_ES',
                'enabled' => true,
                'created_at' => '2022-01-26 03:55:29',
                'updated_at' => '2022-01-26 03:55:29',
                'deleted_at' => NULL,
                'contact_id' => 9,
                'employer_cost' => NULL,
                'competencies' => '[]',
                'working_skills' => '[]',
                'work_experience' => NULL,
                'contract_type' => NULL,
                'contract_start' => NULL,
                'contract_end' => NULL,
                'surname' => 'De Presupuestos Local',
                'personal_phone' => '0995650300',
                'date_birth' => NULL,
                'gender' => NULL,
                'job_title' => NULL,
                'business_phone' => NULL,
                'photo' => NULL,
                'personal_notes' => NULL,
                'company_id' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Técnico',
                'email' => 'toperativo@mail.com',
                'password' => '$2y$10$v2bTq4Y/pvjESlYF9bcpPObZSJjC3e4ITo1HaXldgkNoxfWfgTv2C',
                'remember_token' => NULL,
                'last_logged_in_at' => NULL,
                'locale' => 'en_ES',
                'enabled' => true,
                'created_at' => '2022-01-26 03:56:36',
                'updated_at' => '2022-01-26 03:56:36',
                'deleted_at' => NULL,
                'contact_id' => 10,
                'employer_cost' => NULL,
                'competencies' => '[]',
                'working_skills' => '[]',
                'work_experience' => NULL,
                'contract_type' => NULL,
                'contract_start' => NULL,
                'contract_end' => NULL,
                'surname' => 'Operativo',
                'personal_phone' => '0995650300',
                'date_birth' => NULL,
                'gender' => NULL,
                'job_title' => NULL,
                'business_phone' => NULL,
                'photo' => NULL,
                'personal_notes' => NULL,
                'company_id' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Oficial',
                'email' => 'oficialpmer@mail.com',
                'password' => '$2y$10$ZK5KPX4I55x.7eTXIUpeSeqBD5RDMH4gNDuwnNfRJheJL1znY99la',
                'remember_token' => NULL,
                'last_logged_in_at' => NULL,
                'locale' => 'en_ES',
                'enabled' => true,
                'created_at' => '2022-01-26 03:57:14',
                'updated_at' => '2022-01-26 03:57:14',
                'deleted_at' => NULL,
                'contact_id' => 11,
                'employer_cost' => NULL,
                'competencies' => '[]',
                'working_skills' => '[]',
                'work_experience' => NULL,
                'contract_type' => NULL,
                'contract_start' => NULL,
                'contract_end' => NULL,
                'surname' => ' De Pmer',
                'personal_phone' => '0995650300',
                'date_birth' => NULL,
                'gender' => NULL,
                'job_title' => NULL,
                'business_phone' => NULL,
                'photo' => NULL,
                'personal_notes' => NULL,
                'company_id' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Técnico',
                'email' => 'tespecialista@mail.com',
                'password' => '$2y$10$qMGMgDLu3Zt6jYT7JhwLOOToJI0C.IhZwn4eCipc0GUIjIzSJ/lhK',
                'remember_token' => NULL,
                'last_logged_in_at' => NULL,
                'locale' => 'en_ES',
                'enabled' => true,
                'created_at' => '2022-01-26 03:57:56',
                'updated_at' => '2022-01-26 03:57:56',
                'deleted_at' => NULL,
                'contact_id' => 12,
                'employer_cost' => NULL,
                'competencies' => '[]',
                'working_skills' => '[]',
                'work_experience' => NULL,
                'contract_type' => NULL,
                'contract_start' => NULL,
                'contract_end' => NULL,
                'surname' => ' Especialista',
                'personal_phone' => '0995650300',
                'date_birth' => NULL,
                'gender' => NULL,
                'job_title' => NULL,
                'business_phone' => NULL,
                'photo' => NULL,
                'personal_notes' => NULL,
                'company_id' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Oficial',
                'email' => 'oficialpresupuestos@mail.com',
                'password' => '$2y$10$XeE3QtFrnNzHbYesWzfpWeYqUWv4mpZAw335aJAwHWAwbna3cMHPu',
                'remember_token' => NULL,
                'last_logged_in_at' => NULL,
                'locale' => 'en_ES',
                'enabled' => true,
                'created_at' => '2022-01-26 03:58:28',
                'updated_at' => '2022-01-26 03:58:28',
                'deleted_at' => NULL,
                'contact_id' => 13,
                'employer_cost' => NULL,
                'competencies' => '[]',
                'working_skills' => '[]',
                'work_experience' => NULL,
                'contract_type' => NULL,
                'contract_start' => NULL,
                'contract_end' => NULL,
                'surname' => ' De Presupuestos',
                'personal_phone' => '0995650300',
                'date_birth' => NULL,
                'gender' => NULL,
                'job_title' => NULL,
                'business_phone' => NULL,
                'photo' => NULL,
                'personal_notes' => NULL,
                'company_id' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Oficial',
                'email' => 'oficialpmerlocal@mail.com',
                'password' => '$2y$10$z9xlYRCDbdKBAW6VutA13u54857z33TPV2c9dnPUmLhkKNAUdlB.i',
                'remember_token' => NULL,
                'last_logged_in_at' => NULL,
                'locale' => 'en_ES',
                'enabled' => true,
                'created_at' => '2022-01-26 03:59:05',
                'updated_at' => '2022-01-26 03:59:05',
                'deleted_at' => NULL,
                'contact_id' => 14,
                'employer_cost' => NULL,
                'competencies' => '[]',
                'working_skills' => '[]',
                'work_experience' => NULL,
                'contract_type' => NULL,
                'contract_start' => NULL,
                'contract_end' => NULL,
                'surname' => ' De Pmer Local',
                'personal_phone' => '0995650300',
                'date_birth' => NULL,
                'gender' => NULL,
                'job_title' => NULL,
                'business_phone' => NULL,
                'photo' => NULL,
                'personal_notes' => NULL,
                'company_id' => NULL,
            ),
        ));
        
        
    }
}