version: "3"

services:

  web:
    image: cruzroja.azurecr.io/cre:latest
    env_file: ${PROD_ENV_FILE}
    restart: always
    ports:
      - "8001:80"
    volumes:
       - storage:/app/storage

volumes:
  storage:
